name: CI/CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TESTING: "true"
      SEC_USER_AGENT_EMAIL: "test@example.com"
      NASDAQ_API_KEY: "test_key"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]

    - name: Create test environment file
      run: |
        echo "SEC_USER_AGENT_EMAIL=test@example.com" > test.env
        echo "NASDAQ_API_KEY=test_key" >> test.env
        echo "LOG_LEVEL=DEBUG" >> test.env

    - name: Run Ruff
      run: ruff check src

    - name: Check formatting
      run: black --check .

    - name: Run type checking
      run: mypy src

    - name: Run tests with coverage
      run: pytest --cov=src --cov-report=xml
      
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: .pytest_cache